import { router } from "expo-router";
import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput } from "react-native";
import { Screen } from "../src/components/Screen";
import { validateCredentials } from "../src/domain/auth";
import { useAuthStore } from "../src/store/auth-store";
import { colors } from "../src/theme";

export default function Auth() { const [mode, setMode] = useState<"login" | "register">("login"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false); const login = useAuthStore((s) => s.login); const register = useAuthStore((s) => s.register);
  const submit = async () => { const errors = validateCredentials(email, password); if (mode === "register" && !name.trim()) errors.unshift("Informe como deseja ser chamado."); if (errors.length) return setError(errors.join(" ")); setBusy(true); setError(undefined); try { if (mode === "login") await login(email, password); else await register(name, email, password); router.replace("/"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível entrar."); } finally { setBusy(false); } };
  return <Screen><Text style={styles.title}>{mode === "login" ? "Entrar" : "Criar conta"}</Text><Text style={styles.intro}>O primeiro acesso precisa de internet. Depois, suas lições continuam disponíveis offline.</Text>{mode === "register" && <TextInput accessibilityLabel="Nome" placeholder="Como deseja ser chamado" value={name} onChangeText={setName} style={styles.input} autoCapitalize="words" />}<TextInput accessibilityLabel="E-mail" placeholder="seu@email.com" value={email} onChangeText={setEmail} style={styles.input} keyboardType="email-address" autoCapitalize="none" autoComplete="email" /><TextInput accessibilityLabel="Senha" placeholder="Pelo menos 8 caracteres" value={password} onChangeText={setPassword} style={styles.input} secureTextEntry autoComplete={mode === "login" ? "current-password" : "new-password"} />{error && <Text accessibilityRole="alert" style={styles.error}>{error}</Text>}<Pressable disabled={busy} onPress={() => void submit()} style={styles.primary}><Text style={styles.primaryText}>{busy ? "Aguarde..." : mode === "login" ? "Entrar" : "Criar conta"}</Text></Pressable><Pressable onPress={() => { setMode(mode === "login" ? "register" : "login"); setError(undefined); }} style={styles.link}><Text style={styles.linkText}>{mode === "login" ? "Ainda não tenho conta" : "Já tenho conta"}</Text></Pressable></Screen>;
}
const styles = StyleSheet.create({ title: { fontSize: 32, fontWeight: "800", color: colors.text }, intro: { fontSize: 17, lineHeight: 25, color: colors.muted }, input: { minHeight: 58, borderWidth: 2, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.surface, paddingHorizontal: 16, fontSize: 18, color: colors.text }, error: { color: colors.danger, fontSize: 16, lineHeight: 23 }, primary: { minHeight: 60, borderRadius: 15, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" }, primaryText: { color: "white", fontSize: 18, fontWeight: "800" }, link: { minHeight: 52, alignItems: "center", justifyContent: "center" }, linkText: { color: colors.primary, fontWeight: "700", fontSize: 17 } });
