import { Link, Redirect } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { AudioButton } from "../src/components/AudioButton";
import { Screen } from "../src/components/Screen";
import { colors } from "../src/theme";
import { useAuthStore } from "../src/store/auth-store";

export default function Home() { const status = useAuthStore((state) => state.status); if (status === "anonymous") return <Redirect href="/auth" />; return <Screen><View><Text style={styles.eyebrow}>APRENDER NO SEU RITMO</Text><Text style={styles.title}>Olá! Vamos praticar?</Text><Text style={styles.body}>Atividades curtas e guiadas por áudio.</Text></View><AudioButton label="Ouvir boas-vindas" text="Olá! Vamos praticar? Aprenda no seu ritmo." /><Link href="/lessons" asChild><Pressable style={styles.primary} accessibilityRole="button"><Text style={styles.primaryText}>Começar estudo</Text></Pressable></Link><Link href="/progress" asChild><Pressable style={styles.secondary} accessibilityRole="button"><Text style={styles.secondaryText}>Ver meu progresso</Text></Pressable></Link><Text style={styles.privacy}>Guardamos apenas o resultado das atividades para acompanhar seu progresso.</Text></Screen>; }
const styles = StyleSheet.create({ eyebrow: { color: colors.accent, fontSize: 14, fontWeight: "800", letterSpacing: 1 }, title: { color: colors.text, fontSize: 34, fontWeight: "800", marginTop: 8 }, body: { color: colors.muted, fontSize: 19, lineHeight: 28, marginTop: 10 }, primary: { minHeight: 64, backgroundColor: colors.primary, borderRadius: 16, alignItems: "center", justifyContent: "center" }, primaryText: { color: "white", fontSize: 20, fontWeight: "800" }, secondary: { minHeight: 60, borderWidth: 2, borderColor: colors.primary, borderRadius: 16, alignItems: "center", justifyContent: "center" }, secondaryText: { color: colors.primary, fontSize: 18, fontWeight: "700" }, privacy: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: "auto" } });
