import { Link } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Screen } from "../src/components/Screen";
import { LETTERS } from "../src/domain/catalog";
import { useStudyStore } from "../src/store/study-store";
import { colors } from "../src/theme";

export default function Lessons() { const progress = useStudyStore((state) => state.progress); return <Screen><Text style={styles.title}>Trilha de aprendizagem</Text><Text style={styles.intro}>Aprenda em pequenas etapas. Você pode revisar uma letra já praticada.</Text>{[1, 2, 3].map((phase) => { const items = LETTERS.filter((lesson) => lesson.phase === phase); return <View key={phase}><Text style={styles.phaseTitle}>{items[0].phaseTitle}</Text><View style={styles.grid}>{items.map((lesson) => { const done = progress[lesson.id]?.completed; const unlocked = lesson.order === 1 || lesson.prerequisiteLetters.every((letter) => progress[`letter-${letter.toLowerCase()}`]?.completed) || done; return <Link key={lesson.id} href={{ pathname: "/lesson/[id]", params: { id: lesson.id } }} asChild><Pressable disabled={!unlocked} accessibilityLabel={`Letra ${lesson.letter}${done ? ", concluída" : !unlocked ? ", bloqueada" : ""}`} style={StyleSheet.flatten([styles.tile, done && styles.done, !unlocked && styles.locked])}><Text style={[styles.letter, done && styles.doneText]}>{unlocked ? lesson.letter : "•"}</Text><Text style={[styles.state, done && styles.doneText]}>{done ? "Concluída" : unlocked ? `Lição ${lesson.order}` : "Bloqueada"}</Text></Pressable></Link>; })}</View></View>; })}</Screen>; }
const styles = StyleSheet.create({ title: { fontSize: 30, fontWeight: "800", color: colors.text }, intro: { fontSize: 17, lineHeight: 25, color: colors.muted }, phaseTitle: { fontSize: 21, fontWeight: "800", color: colors.text, marginTop: 18 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 12 }, tile: { width: "30%", minWidth: 88, minHeight: 100, borderRadius: 16, borderWidth: 2, borderColor: colors.border, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center" }, done: { backgroundColor: colors.success, borderColor: colors.success }, locked: { opacity: 0.5 }, letter: { fontSize: 38, fontWeight: "800", color: colors.primary }, state: { fontSize: 12, color: colors.muted }, doneText: { color: "white" } });
