import { useQuery } from "@tanstack/react-query";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Screen } from "../src/components/Screen";
import { LETTERS } from "../src/domain/catalog";
import { getProgress } from "../src/storage/database";
import { useSync } from "../src/sync/use-sync";
import { colors } from "../src/theme";

export default function Progress() { const query = useQuery({ queryKey: ["progress"], queryFn: getProgress }); const sync = useSync(); const completed = query.data?.filter((item) => item.completed).length ?? 0; return <Screen><Text style={styles.title}>Meu progresso</Text><View style={styles.card}><Text style={styles.number}>{completed} de {LETTERS.length}</Text><Text style={styles.label}>letras dominadas</Text><View accessibilityRole="progressbar" accessibilityValue={{ min: 0, max: 26, now: completed }} style={styles.track}><View style={[styles.fill, { width: `${(completed / 26) * 100}%` }]} /></View></View><View style={styles.phases}>{[1, 2, 3].map((phase) => { const phaseLetters = LETTERS.filter((item) => item.phase === phase); const phaseCompleted = phaseLetters.filter((item) => query.data?.some((progress) => progress.lessonId === item.id && progress.completed)).length; return <View key={phase} style={styles.phase}><Text style={styles.phaseTitle}>{phaseLetters[0].phaseTitle}</Text><Text style={styles.phaseLabel}>{phaseCompleted} de {phaseLetters.length} concluídas</Text></View>; })}</View><Pressable disabled={sync.isPending} onPress={() => sync.mutate()} style={styles.button}><Text style={styles.buttonText}>{sync.isPending ? "Sincronizando..." : "Sincronizar agora"}</Text></Pressable>{sync.isSuccess && <Text accessibilityRole="alert" style={styles.success}>{sync.data ? `${sync.data} item(ns) sincronizado(s).` : "Tudo está atualizado."}</Text>}{sync.isError && <Text accessibilityRole="alert" style={styles.warning}>Você continua no modo offline. Tentaremos novamente depois.</Text>}<Text style={styles.note}>O progresso fica salvo neste aparelho e entra numa fila segura quando não há conexão.</Text></Screen>; }
const styles = StyleSheet.create({ title: { fontSize: 30, color: colors.text, fontWeight: "800" }, card: { backgroundColor: colors.surface, padding: 22, borderRadius: 18 }, number: { fontSize: 36, fontWeight: "800", color: colors.primary }, label: { fontSize: 17, color: colors.muted }, track: { height: 14, borderRadius: 7, backgroundColor: colors.border, overflow: "hidden", marginTop: 16 }, fill: { height: "100%", backgroundColor: colors.success }, phases: { gap: 10 }, phase: { backgroundColor: colors.surface, borderRadius: 14, padding: 16 }, phaseTitle: { color: colors.text, fontWeight: "800", fontSize: 17 }, phaseLabel: { color: colors.muted, fontSize: 15, marginTop: 4 }, button: { minHeight: 60, borderRadius: 15, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" }, buttonText: { color: "white", fontSize: 18, fontWeight: "700" }, success: { color: colors.success, fontSize: 16 }, warning: { color: colors.danger, fontSize: 16 }, note: { color: colors.muted, fontSize: 16, lineHeight: 24 } });
